remote_theme: pmarsceill/just-the-docs
title: Home Automation India
description: A Community driven site to host various documentaion contributed by community members to help users get started with Home Automation and related services.
search_enabled: true
color_scheme: dark
